import type { Metadata } from "next";
import '@mantine/core/styles.css';
import '@mantine/dates/styles.css';
import '@mantine/carousel/styles.css';
import { Box, ColorSchemeScript, mantineHtmlProps, MantineProvider, Space, Stack } from "@mantine/core";
import { RootStyleRegistry } from "./EmotionRootStyleRegistry";
import { emotionTransform, MantineEmotionProvider } from "@mantine/emotion";
import { HeaderComponent } from "@/components/HeaderComponent";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr" {...mantineHtmlProps}>
      <head>
        <ColorSchemeScript />
      </head>
      <body suppressHydrationWarning>
        <RootStyleRegistry>
          <MantineEmotionProvider >
            <MantineProvider stylesTransform={emotionTransform} defaultColorScheme="dark">
              <header>
                <HeaderComponent />
              </header>
              <Space h={50} />
              <Box px={{ base: 20, lg: 50 }} py="md">
                <main>
                  <Stack gap={100}>
                    {children}
                  </Stack>
                </main>
              </Box>
            </MantineProvider>
          </MantineEmotionProvider >
        </RootStyleRegistry >
      </body >
    </html >
  );
}
