export const hotelAmenities = [
  {
    label: "Bien-être et loisirs",
    key: "wellness",
    items: [
      "Piscine intérieure",
      "Piscine extérieure",
      "Spa / centre de bien-être",
      "Salle de sport / fitness",
      "Sauna",
      "Hammam",
      "Court de tennis",
      "Parcours de golf",
      "Plage privée",
      "Jardin ou terrasse",
      "Aires de jeux pour enfants",
      "Club enfants / service de garde",
    ],
  },
  {
    label: "Services d'affaires",
    key: "business",
    items: [
      "Centre d'affaires",
      "Salles de conférence",
      "Service de conciergerie",
      "WiFi haut débit",
      "Espaces de coworking",
    ],
  },
  {
    label: "Confort de chambre",
    key: "comfort",
    items: [
      "Balcon / terrasse privée",
      "Baignoire à remous / jacuzzi privatif",
      "Cuisine équipée / kitchenette",
      "Machine à café / thé en chambre",
      "Minibar",
      "Smart TV / système de divertissement",
    ],
  },
  {
    label: "Transport et stationnement",
    key: "transport",
    items: [
      "Parking gratuit",
      "Service voiturier",
      "Station de recharge pour véhicules électriques",
      "Service de navette",
      "Location de vélos",
      "Location de voitures",
      "Service de transport vers l'aéroport",
    ],
  },
  {
    label: "Services supplémentaires",
    key: "addServices",
    items: [
      "Blanchisserie / nettoyage à sec",
      "Chapelle / salle de prière",
      "Boutiques sur place",
      "Bibliothèque",
      "Salle de jeux",
      "Activités organisées par l'hôtel",
      "Service médical / infirmerie",
    ],
  },
];
